name: 'Compile workflow'
description: 'Compile all jobs from workflow to create a status check'
inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: false
  TARGET_RUN_ID:
    description: Target run id
    default: ${{ github.run_id }}
    required: false
  OUTPUT_ENV_NAME:
    description: Env name used for output
    required: false
    default: STATUS
  SET_CONTEXT:
    description: Default check_run context to set for all jobs
    required: false
    default: status
  IGNORE_JOBS:
    description: job patterns to ignore
    required: false
    default: none # (none | all | best-practices*,compliance*,...)

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      working-directory: ${{ github.workflow.action.path }}
      shell: bash
      run: npm ci

    - name: Install dependencies
      working-directory: ${{ github.workflow.action.path }}
      shell: bash
      run: node index.js

outputs:
  status:
    description: Workflow status report
    value: ${{ steps.set-status.outputs.status }}


branding:
  icon: 'check-circle'
  color: 'green'
