name: Workflow run check
description: Create a check run from the result of all jobs in a workflow run
inputs:
  github-token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: false
  target-run-id:
    description: Target run id
    default: ${{ github.run_id }}
    required: false
  check-run-name:
    description: Check_run name (used to set as required check to block merging PRs)
    default: status
    required: false
  check-run-title:
    description: Check_run title
    default: title
    required: false
  ignore-jobs:
    description: Job patterns to ignore
    required: false
runs:
  using: node16
  main: dist/index.js
branding:
  icon: check-circle
  color: green