name: 'Compile workflow'
description: 'Compile all jobs from workflow to create a status check'
inputs:
  github-token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: false
  target-run-id:
    description: Target run id
    default: ${{ github.run_id }}
    required: false
  set-context:
    description: Default check_run context to set for all jobs
    required: false
    default: status
  ignore-jobs:
    description: job patterns to ignore
    required: false
    default: ".*Best-practice|Report|compile*" # (none | all | best-practices*,compliance*,...)

runs:
  using: 'node16'
  main: 'dist/index.js'


outputs:
  status:
    description: Workflow status report


branding:
  icon: 'check-circle'
  color: 'green'
