name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  one:
    name: First
    runs-on: ubuntu-latest
    steps:
      - run: echo Hi

  two:
    name: Two
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello

  check-run-defaults:
    name: Check run (defaults)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
